name = "KIRO2025"
uuid = "f3329797-4000-4b84-b601-9e763a91dd0e"
authors = [""]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
CSV = "0.10.15"
Conda = "1.10.3"
DataFrames = "1.8.1"
PlotlyJS = "0.18.17"
Plots = "1.41.1"
PyCall = "1.96.4"
